{"name": "test_login", "status": "broken", "statusDetails": {"message": "UnboundLocalError: local variable 'error' referenced before assignment", "trace": "self = <test_login_i.TestLogin object at 0x1039561c0>\n\n    def test_login(self):\n        try:\n            driver = self.driver\n            driver.get(utils.URL)\n            login = LoginPage(driver)\n            login.enter_username(utils.USERNAME)\n            login.enter_password(utils.PASSWORD)\n            login.click_login()\n            time.sleep(4)\n            home_page = driver.title\n            assert home_page == \"Course Materials | Pearson1\"\n            home_page = HomePage(driver)\n            home_page.click_menu_instructor()\n            home_page.click_account_settings()\n            user_name_displayed = driver.find_element_by_id(\"displayedUsername\").text\n            assert user_name_displayed == utils.USERNAME\n        except AssertionError as error:\n            print(\"Assertion error occurred\")\n>       print(error)\nE       UnboundLocalError: local variable 'error' referenced before assignment\n\nTests/Instructor/test_login_i.py:40: UnboundLocalError"}, "attachments": [{"name": "stdout", "source": "7af575d4-e30c-447d-a087-ee0e6dec3f9a-attachment.txt", "type": "text/plain"}], "start": 1580145798292, "stop": 1580145806597, "uuid": "e13da551-8cf7-4d5a-b28b-b939175ca1d8", "historyId": "c31cf62fa6afeb23e503055889de484c", "testCaseId": "d3caa846cd5ed721ded9a3a35783b148", "fullName": "Tests.Instructor.test_login_i.TestLogin#test_login", "labels": [{"name": "parentSuite", "value": "Tests.Instructor"}, {"name": "suite", "value": "test_login_i"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "SNFCAML-X0FJG3Q"}, {"name": "thread", "value": "35955-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Tests.Instructor.test_login_i"}]}